name: Run Existing File Monitor (system Python)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "30 16 * * 0"   # Sundays 22:00 IST approx; adjust

jobs:
  run-monitor:
    runs-on: self-hosted
    timeout-minutes: 120

    env:
      # Absolute paths on the runner
      PYTHON_EXE: C:\Users\User\AppData\Local\Programs\Python\Python313\python.exe
      SCRIPT_PATH: C:\FileSystemMonitor\FileSystemMonitor.py

      # Runtime config for your script
      BASE_PATHS: C:\asif pala\samples
      ES_URL: https://localhost:9200
      ES_INDEX: file-monitor
      ES_USERNAME: elastic
      ES_PASSWORD: mGUt6fo9Hj=V7saEVatU
      ES_VERIFY_CERTS: "false"
      ES_TIMEOUT: "60"

    steps:
      - name: Verify Python path
        shell: cmd
        run: |
          "%PYTHON_EXE%" --version || (echo FATAL: Python path invalid & exit /b 1)

      - name: Install/upgrade required packages (once per machine is enough)
        shell: cmd
        run: |
          "%PYTHON_EXE%" -m pip install --upgrade pip
          "%PYTHON_EXE%" -m pip install blake3 "elasticsearch>=8.12.0"

      - name: Run monitor (existing script)
        shell: cmd
        run: |
          rem Pass env vars to the script; ensure your script reads them (ES_URL, ES_USERNAME, etc.)
          "%PYTHON_EXE%" "%SCRIPT_PATH%"

      - name: Upload CSV and logs
        uses: actions/upload-artifact@v4
        with:
          name: monitor-output
          path: |
            C:\FileSystemMonitor\file_scan_*.csv
            C:\FileSystemMonitor\moved_files_*.csv
            C:\FileSystemMonitor\file_monitor.log
          if-no-files-found: warn
