name: Hash and Ingest to Elasticsearch

on:
  workflow_dispatch:   # Manual trigger from Actions tab
  schedule:           # Auto-run weekly, Monday 4:00 AM UTC
    - cron: '*/2 * * * *' #'0 4 * * 1'

jobs:
  hash-and-ingest:
    runs-on: self-hosted
    steps:
      - name: Checkout Code (if needed)
        uses: actions/checkout@v4

      - name: Generate SHA256 CSV
        id: generate_hash
        shell: powershell
        run: |
          $folderPath = "C:\\asif pala\\samples"
          $timestamp = Get-Date -Format "yyyy-MM-dd"
          $outputCsv = "C:\\asif pala\\output\\testing_$timestamp.csv"

          $hashResults = @()
          Get-ChildItem -Path $folderPath -Recurse -File | ForEach-Object {
              try {
                  $fileHash = Get-FileHash -Algorithm SHA256 -Path $_.FullName
                  $obj = [PSCustomObject]@{
                      FileName = $_.Name
                      FullPath = $_.FullName
                      SHA256   = $fileHash.Hash
                  }
                  $hashResults += $obj
                  Write-Host "Hashed: $($_.FullName)"
              }
              catch {
                  Write-Warning "Failed to hash $($_.FullName): $_"
              }
          }
          $hashResults | Export-Csv -Path $outputCsv -NoTypeInformation -Encoding UTF8
          Write-Host "`nSHA-256 hashes generated and saved to:`n$outputCsv"

          # Set outputs for use in next step
          Write-Host "::set-output name=timestamp::$timestamp"
          Write-Host "::set-output name=csv_path::$outputCsv"

      - name: Ingest with Logstash
        env:
          CSV_PATH: ${{ steps.generate_hash.outputs.csv_path }}
          DATE: ${{ steps.generate_hash.outputs.timestamp }}
        run: |
          "C:\\asif pala\\logstash-9.1.0-windows-x86_64\\logstash-9.1.0\\bin\\logstash.bat" -f "C:\\asif pala\\logstash-9.1.0-windows-x86_64\\logstash-9.1.0\\config\\sample.conf"

      # Optional: Add step here to update and start Elasticsearch Transform if needed
